const products = [
  {id:'cookie',name:'Печенье с кусочками шоколада',category:'Печенье',group:'sweets',emoji:'🍪',weight:'180 г',price:129,tag:'Хит',hit:true},
  {id:'milk-choc',name:'Молочный шоколад с фундуком',category:'Шоколад',group:'sweets',emoji:'🍫',weight:'90 г',price:99,tag:'Новинка',new:true,hit:true},
  {id:'chips',name:'Хрустящие чипсы с морской солью',category:'Чипсы и снеки',group:'snacks',emoji:'🥔',weight:'70 г',price:75,tag:'',hit:true},
  {id:'lemonade',name:'Лимонад с натуральным лимоном',category:'Напитки',group:'drinks',emoji:'🥤',weight:'330 мл',price:89,tag:'',new:true},
  {id:'candy',name:'Мармеладные мишки',category:'Конфеты',group:'sweets',emoji:'🧸',weight:'150 г',price:115,tag:'Новинка',new:true},
  {id:'wafer',name:'Вафли с нежной начинкой',category:'Вафли',group:'sweets',emoji:'🧇',weight:'200 г',price:104,tag:'Хит',hit:true},
  {id:'juice',name:'Яблочный сок',category:'Напитки',group:'drinks',emoji:'🧃',weight:'200 мл',price:49,tag:'',hit:true},
  {id:'pretzel',name:'Солёные крендельки',category:'Чипсы и снеки',group:'snacks',emoji:'🥨',weight:'100 г',price:69,tag:'',new:true},
  {id:'croissant',name:'Круассан с шоколадом',category:'Выпечка',group:'sweets',emoji:'🥐',weight:'75 г',price:59,tag:'Хит',hit:true},
  {id:'tea',name:'Чёрный чай с бергамотом',category:'Чай и кофе',group:'drinks',emoji:'🍵',weight:'25 пакетиков',price:189,tag:'',new:true},
  {id:'nuts',name:'Арахис жареный солёный',category:'Орехи',group:'snacks',emoji:'🥜',weight:'120 г',price:99,tag:'Хит',hit:true},
  {id:'cereal',name:'Хлопья с мёдом',category:'Завтраки',group:'grocery',emoji:'🥣',weight:'250 г',price:149,tag:'',new:true},
  {id:'honey',name:'Мёд цветочный',category:'Бакалея',group:'grocery',emoji:'🍯',weight:'300 г',price:229,tag:'',hit:true},
  {id:'popcorn',name:'Попкорн карамельный',category:'Чипсы и снеки',group:'snacks',emoji:'🍿',weight:'90 г',price:79,tag:'Новинка',new:true},
  {id:'cocoa',name:'Какао напиток',category:'Чай и кофе',group:'drinks',emoji:'☕',weight:'200 г',price:169,tag:'',new:true},
  {id:'soap',name:'Мыло для рук с ароматом цитруса',category:'Для дома',group:'home',emoji:'🧼',weight:'90 г',price:79,tag:'',new:true},
  {id:'toy',name:'Мягкая игрушка-медвежонок',category:'Для детей',group:'kids',emoji:'🧸',weight:'1 шт.',price:349,tag:'',hit:true},
  {id:'gummies',name:'Жевательный мармелад',category:'Конфеты',group:'sweets',emoji:'🍬',weight:'100 г',price:89,tag:'Хит',hit:true},
  {id:'marshmallow',name:'Зефир ванильный',category:'Зефир и мармелад',group:'sweets',emoji:'🍡',weight:'180 г',price:119,tag:'Новинка',new:true},
  {id:'lemon-cookie',name:'Песочное печенье с лимоном',category:'Печенье',group:'sweets',emoji:'🍋',weight:'160 г',price:109,tag:'Новинка',new:true},
  {id:'choco-bar',name:'Шоколадный батончик с карамелью',category:'Батончики',group:'sweets',emoji:'🍫',weight:'50 г',price:64,tag:'Новинка',new:true},
  {id:'dried-fruit',name:'Сушёное манго',category:'Сушёные фрукты',group:'snacks',emoji:'🥭',weight:'80 г',price:139,tag:'Новинка',new:true},
  {id:'sesame-cracker',name:'Крекеры с кунжутом',category:'Крекеры',group:'snacks',emoji:'🍘',weight:'130 г',price:84,tag:'Новинка',new:true},
  {id:'popcorn-cheese',name:'Попкорн со вкусом сыра',category:'Чипсы и снеки',group:'snacks',emoji:'🍿',weight:'80 г',price:74,tag:'Новинка',new:true},
  {id:'berry-juice',name:'Морс из лесных ягод',category:'Соки и нектары',group:'drinks',emoji:'🧃',weight:'300 мл',price:79,tag:'Новинка',new:true},
  {id:'spice-cocoa',name:'Какао с корицей',category:'Чай и кофе',group:'drinks',emoji:'☕',weight:'180 г',price:179,tag:'Новинка',new:true},
  {id:'tomato-sauce',name:'Томатный соус с травами',category:'Соусы',group:'grocery',emoji:'🍅',weight:'250 г',price:129,tag:'Новинка',new:true},
  {id:'oat-cookies',name:'Овсяное печенье с мёдом',category:'Печенье',group:'sweets',emoji:'🍪',weight:'220 г',price:119,tag:'Новинка',new:true},
  {id:'caramel-candy',name:'Карамель фруктовая',category:'Конфеты',group:'sweets',emoji:'🍭',weight:'120 г',price:69,tag:'Новинка',new:true}
];
const categories=[
  ['sweets','Сладости и десерты','🍭',['Конфеты','Печенье','Вафли','Шоколад','Батончики','Зефир и мармелад']],
  ['snacks','Снеки и орехи','🥨',['Семечки','Сухарики и гренки','Орехи','Чипсы','Попкорн','Сушёные фрукты']],
  ['grocery','Бакалея','🫙',['Мука','Соусы и кетчупы','Масло и оливки','Макаронные изделия','Консервация','Специи и приправы']],
  ['drinks','Чай, кофе и напитки','☕',['Чай','Соки и нектары','Кофе и какао','Вода','Компоты','Молочные напитки']],
  ['home','Для дома','🧽',['Гигиена и уход','Кухонные принадлежности','Средства для уборки','Батарейки и зажигалки','Пакеты','Товары для дома']],
  ['kids','Для детей','🧸',['Игрушки','Творчество и игры','Детское питание','Детская гигиена','Наборы сладостей','Школьные товары']]
];
const money=n=>`${Number(n).toLocaleString('ru-RU')} ₽`;
function readCart(){try{return JSON.parse(localStorage.getItem('tmb-cart')||'{}')}catch{return {}}}
let cart=readCart();
function readFavorites(){try{return JSON.parse(localStorage.getItem('tmb-favorites')||'[]')}catch{return []}}
let favorites=readFavorites();
function isFavorite(id){return favorites.includes(id)}
function saveCart(){try{localStorage.setItem('tmb-cart',JSON.stringify(cart))}catch{}}
function qty(id){return Number(cart[id]||0)}
function cartCount(){return Object.values(cart).reduce((a,b)=>a+Number(b),0)}
function productCard(p){const favorite=isFavorite(p.id);return `<article class="product"><a href="product.html?id=${encodeURIComponent(p.id)}"><div class="product-image" role="img" aria-label="${p.name}">${p.emoji}${p.tag?`<span class="tag ${p.tag==='Новинка'?'tag-new':'tag-hit'}">${p.tag}</span>`:''}</div></a><div class="product-info"><div class="product-meta"><span class="price">${money(p.price)}</span><span class="muted">${p.weight}</span></div><h3><a href="product.html?id=${encodeURIComponent(p.id)}">${p.name}</a></h3><div class="product-actions"><button class="add-button" data-add="${p.id}" aria-label="Добавить ${p.name} в корзину">В корзину</button><button class="favorite-button${favorite?' is-favorite':''}" data-favorite="${p.id}" aria-label="${favorite?'Убрать из':'Добавить в'} избранное: ${p.name}" aria-pressed="${favorite}">${favorite?'♥':'♡'}</button></div></div></article>`}
function productGrid(list){return list.length?list.map(productCard).join(''):'<p class="empty-results">По вашему запросу ничего не найдено. Измените фильтр или поиск.</p>'}
function header(){return `<header class="header"><div class="wrap"><div class="header-main"><a class="brand" href="index.html" aria-label="ТМВ — главная"><span class="brand-mark">ТМВ</span></a><label class="search"><span aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.5"></circle><path d="m15.7 15.7 4.2 4.2"></path></svg></span><input id="site-search" type="search" placeholder="Найти в ТМВ" aria-label="Поиск товаров"></label><div class="header-actions"><label class="address-field" aria-label="Адрес доставки"><span aria-hidden="true">📍</span><input id="address-input" type="text" placeholder="Указать адрес" autocomplete="street-address" readonly aria-haspopup="dialog"></label><button class="login-button" id="login-button" type="button" aria-label="Войти" title="Войти"><span class="login-glyph" aria-hidden="true">→]</span></button></div></div></div></header>`}
function catalogSidebar(){const emojiFor=name=>{const n=name.toLocaleLowerCase('ru');if(n.includes('конфет')||n.includes('карамел'))return '🍬';if(n.includes('печень'))return '🍪';if(n.includes('вафл'))return '🧇';if(n.includes('шоколад')||n.includes('батон'))return '🍫';if(n.includes('зефир')||n.includes('мармелад'))return '🍡';if(n.includes('семеч'))return '🌻';if(n.includes('сухар')||n.includes('грен'))return '🥖';if(n.includes('орех'))return '🥜';if(n.includes('чипс'))return '🥔';if(n.includes('попкорн'))return '🍿';if(n.includes('фрукт'))return '🥭';if(n.includes('мука'))return '🌾';if(n.includes('соус')||n.includes('кетчуп'))return '🍅';if(n.includes('масло'))return '🫒';if(n.includes('макарон'))return '🍝';if(n.includes('консер'))return '🥫';if(n.includes('спец'))return '🧂';if(n.includes('чай'))return '🍵';if(n.includes('сок')||n.includes('нектар'))return '🧃';if(n.includes('кофе')||n.includes('какао'))return '☕';if(n.includes('вод'))return '💧';if(n.includes('компот'))return '🫙';if(n.includes('молоч'))return '🥛';if(n.includes('гигиен'))return '🧼';if(n.includes('кухон'))return '🍽️';if(n.includes('уборк'))return '🧽';if(n.includes('батар'))return '🔋';if(n.includes('пакет'))return '🛍️';if(n.includes('игруш'))return '🧸';if(n.includes('творч')||n.includes('игр'))return '🎨';if(n.includes('детск'))return '🍼';if(n.includes('набор'))return '🎁';if(n.includes('школь'))return '✏️';return '✨'};return `<h2>Каталог</h2><a class="catalog-shortcut" href="catalog.html"><span class="category-emoji">📦</span><strong>Все товары</strong></a><a class="catalog-shortcut" href="catalog.html?badge=new"><span class="category-emoji">✨</span><strong>Новинки</strong></a><a class="catalog-shortcut" href="catalog.html?badge=hit"><span class="category-emoji">🔥</span><strong>Хиты продаж</strong></a><div class="category-groups">${categories.map(c=>`<section class="catalog-category"><a class="category-heading" href="catalog.html?category=${c[0]}"><span class="category-emoji">${c[2]}</span><strong>${c[1]}</strong></a><div class="category-sublist">${c[3].map(name=>`<a href="catalog.html?category=${c[0]}&sub=${encodeURIComponent(name)}"><span aria-hidden="true">${emojiFor(name)}</span><span>${name}</span></a>`).join('')}</div></section>`).join('')}</div>`}
function footer(){return `<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark">ТМВ</span></a><p>Учебный магазин продуктов и хорошего настроения.</p></div><div><h3>Покупателям</h3><a href="about.html">О магазине</a><a href="delivery.html">Доставка</a><a href="payment.html">Оплата</a><a href="cart.html">Корзина · ${cartCount()}</a></div><div><h3>Каталог</h3><a href="catalog.html?category=sweets">Сладости</a><a href="catalog.html?category=snacks">Снеки</a><a href="catalog.html?category=drinks">Напитки</a><a href="catalog.html">Все товары</a></div><div><h3>Связаться</h3><a href="contacts.html">Контакты</a><a href="mailto:hello@tmb.example">hello@tmb.example</a></div></div><div class="footer-bottom">© 2026 ТМВ маркет · Демоверсия для обучения</div></div></footer>`}
function updateHeader(){const badge=document.querySelector('#cart-count');if(badge){badge.textContent=cartCount();badge.style.display=cartCount()?'inline-block':'none'}document.querySelectorAll('.product-actions [data-add]').forEach(b=>b.textContent='В корзину')}
function toast(message){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),1400)}
function add(id,amount=1){cart[id]=Math.max(0,qty(id)+amount);if(!cart[id])delete cart[id];saveCart();updateHeader();const card=document.querySelector(`[data-add="${id}"]`);if(card&&!card.closest('.product-actions'))card.textContent=qty(id)||'+'}
function rail(id,list){return `<div class="rail-shell"><div class="products product-rail" id="${id}">${productGrid(list)}</div><button class="rail-arrow" type="button" data-scroll-rail="${id}" aria-label="Прокрутить товары вправо">→</button></div>`}
function homePage(){const novelties=products.filter(p=>p.new);const brands=['Сладкий двор','Хруст&Ко','Лакомка','Пекарня №1','Лимон и мята','Доброе утро','Мастерская вкуса','Ягодный берег','Золотая ложка','Снежный мишка','Весёлый перекус','Домашний запас'];const homeCategoryOrder=['drinks','grocery','snacks','sweets','home','kids'];return `<div class="notice" id="delivery-notice"><span>Москва: доставка продуктов от 1 дня. Стоимость и доступность в этой демоверсии условные.</span><button class="notice-close" type="button" aria-label="Закрыть предупреждение">×</button></div><section class="new-arrivals"><div class="section-head"><h2>Новинки</h2></div>${rail('new-products',novelties)}</section><section class="brands-section"><div class="brand-rail"><div class="brand-list" id="brand-list">${brands.map(name=>`<a href="catalog.html">${name}</a>`).join('')}</div><button class="rail-arrow" type="button" data-scroll-rail="brand-list" aria-label="Прокрутить марки вправо">→</button></div></section><section class="more-arrivals"><div class="section-head"><h2>Хиты</h2></div>${rail('hit-products',products.filter(p=>p.hit))}</section>${homeCategoryOrder.map(key=>{const c=categories.find(item=>item[0]===key);return `<section class="category-rail"><div class="section-head"><h2>${c[2]} ${c[1]}</h2></div><div class="category-products products">${productGrid(products.filter(p=>p.group===c[0]))}</div></section>`}).join('')}`}
function catalogPage(){const params=new URLSearchParams(location.search);const cat=params.get('category')||'all';const badge=params.get('badge');const sub=params.get('sub');const names=Object.fromEntries(categories.map(c=>[c[0],c[1]]));let list=products.filter(p=>(cat==='all'||p.group===cat)&&(!badge||p[badge])&&(!sub||(`${p.category} ${p.name}`).toLocaleLowerCase('ru').includes(sub.toLocaleLowerCase('ru'))));const title=sub||((badge==='new'?'Новинки':badge==='hit'?'Хиты':names[cat]||'Каталог товаров'));return `<div class="breadcrumbs"><a href="index.html">Главная</a> / Каталог / ${title}</div><div class="section-head"><h1>${title}</h1><span class="muted">${list.length} товаров</span></div><section><div class="catalog-tools"><span class="muted" id="catalog-count">Показано ${list.length} товаров</span><select id="sort-products" aria-label="Сортировка"><option value="popular">Сначала популярные</option><option value="cheap">Сначала дешевле</option><option value="expensive">Сначала дороже</option></select></div><div class="products" id="catalog-products">${productGrid(list)}</div></section>`}
function detailPage(){const id=new URLSearchParams(location.search).get('id');const p=products.find(item=>item.id===id)||products[0];return `<div class="breadcrumbs"><a href="index.html">Главная</a> / <a href="catalog.html">Каталог</a> / ${p.category}</div><section class="product-detail"><div class="detail-emoji" role="img" aria-label="${p.name}">${p.emoji}</div><div class="detail-info"><p class="muted">${p.category} · ${p.weight}</p><h1>${p.name}</h1><p class="muted">Артикул: TMB-${p.id.toUpperCase()}</p><p class="price">${money(p.price)}</p><p>Вкусный продукт для перекуса и хорошего настроения. Описание и характеристики приведены как пример для учебного магазина.</p><button class="primary" data-add="${p.id}">${qty(p.id)?`В корзине: ${qty(p.id)} · добавить ещё`:'Добавить в корзину'}</button><p class="muted">Количество в корзине: <strong id="detail-qty">${qty(p.id)}</strong></p></div></section><section><div class="section-head"><h2>Вам может понравиться</h2></div><div class="products">${productGrid(products.filter(item=>item.id!==p.id).slice(0,4))}</div></section>`}
function cartPage(){const lines=Object.entries(cart).map(([id,n])=>({p:products.find(p=>p.id===id),n:Number(n)})).filter(x=>x.p);if(!lines.length)return `<div class="breadcrumbs"><a href="index.html">Главная</a> / Корзина</div><div class="section-head"><h1>Корзина</h1></div><div class="empty-state"><p>Корзина пока пуста.</p><a class="primary" href="catalog.html">Перейти в каталог</a></div>`;const total=lines.reduce((s,x)=>s+x.p.price*x.n,0);return `<div class="breadcrumbs"><a href="index.html">Главная</a> / Корзина</div><div class="section-head"><h1>Корзина</h1><button class="chip" id="clear-cart">Очистить корзину</button></div><div class="cart-list">${lines.map(x=>`<div class="cart-line"><div><strong>${x.p.emoji} ${x.p.name}</strong><div class="muted">${x.p.weight} · ${money(x.p.price)} за штуку</div></div><div class="quantity"><button data-cart="minus" data-id="${x.p.id}" aria-label="Уменьшить количество">−</button><strong>${x.n}</strong><button data-cart="plus" data-id="${x.p.id}" aria-label="Увеличить количество">+</button></div><strong class="line-price">${money(x.p.price*x.n)}</strong></div>`).join('')}</div><div class="cart-summary"><div><span class="muted">Итого за товары</span><br><strong class="price">${money(total)}</strong></div><button class="primary" id="checkout">Оформить заказ</button></div><p class="muted">Демо: заказ не отправляется и оплата не списывается.</p>`}
function infoPage(page){const data={about:['О магазине','ТМВ маркет — учебный пример интернет-магазина. Здесь можно посмотреть каталог, поиск, карточку товара и корзину. Все товары, цены и условия доставки демонстрационные.'],delivery:['Доставка','В этой демоверсии доставка условная. В настоящем магазине здесь указывают зоны и сроки доставки, минимальную сумму заказа и стоимость. Адрес можно ввести в шапке сайта.'],payment:['Оплата','Реальную оплату эта учебная версия не принимает. Для настоящего магазина подключают платёжный сервис, который безопасно обрабатывает платёж и возвращает результат.'],contacts:['Контакты','Учебная служба поддержки: hello@tmb.example. Адрес и телефон приведены для примера и не обслуживают реальные заказы.']}[page]||['Информация','Страница учебного магазина.'];return `<div class="breadcrumbs"><a href="index.html">Главная</a> / ${data[0]}</div><div class="section-head"><h1>${data[0]}</h1></div><article class="info-card"><h2>${data[0]} ТМВ маркет</h2><p>${data[1]}</p><p><a class="primary" href="catalog.html">Перейти к покупкам</a></p></article>`}
const page=document.body.dataset.page;
document.querySelector('#site-header').innerHTML=header();document.querySelector('#site-catalog').innerHTML=catalogSidebar();document.querySelector('#site-footer').innerHTML=footer();
document.body.insertAdjacentHTML('beforeend','<dialog id="login-dialog"><div class="dialog-head"><h2>Вход в магазин</h2><button class="dialog-close" type="button" aria-label="Закрыть">×</button></div><form class="dialog-body" id="login-form"><label>Телефон или электронная почта<br><input name="login" type="text" autocomplete="username" required placeholder="+7 900 000-00-00"></label><p class="muted">В демоверсии настоящий вход не подключён.</p><button class="primary">Продолжить</button></form></dialog>');
document.body.insertAdjacentHTML('beforeend',`<dialog id="delivery-dialog" class="delivery-dialog"><div class="dialog-head"><h2>Укажите адрес</h2><button class="dialog-close" type="button" data-close-delivery aria-label="Закрыть">×</button></div><form class="delivery-body" id="delivery-form"><div class="delivery-modes" role="group" aria-label="Способ получения"><button type="button" class="delivery-mode is-active" data-delivery-mode="pickup" aria-pressed="true">Самовывоз</button><button type="button" class="delivery-mode" data-delivery-mode="courier" aria-pressed="false">Курьер</button></div><div class="map-panel" role="img" aria-label="Схема карты с местом доставки"><svg viewBox="0 0 720 260" aria-hidden="true" preserveAspectRatio="xMidYMid slice"><rect width="720" height="260" fill="#e9eee6"/><path d="M-20 54 180 116 340 90 500 132 750 74M-20 210 150 170 330 215 520 180 750 230M110-15 160 85 135 175 195 275M390-15 360 76 405 145 370 275M600-15 545 85 590 160 550 275" fill="none" stroke="#fff" stroke-width="18" stroke-linecap="round"/><path d="M-20 54 180 116 340 90 500 132 750 74M-20 210 150 170 330 215 520 180 750 230M110-15 160 85 135 175 195 275M390-15 360 76 405 145 370 275M600-15 545 85 590 160 550 275" fill="none" stroke="#d6dbd2" stroke-width="2"/><rect x="228" y="34" width="72" height="40" rx="8" fill="#d9e8d3"/><rect x="438" y="164" width="88" height="34" rx="8" fill="#d9e8d3"/><circle cx="360" cy="128" r="22" fill="#f47745" stroke="#fff" stroke-width="6"/><circle cx="360" cy="128" r="6" fill="#fff"/></svg><span class="map-label">Москва</span></div><label class="delivery-address-label" for="delivery-address">Адрес доставки</label><p class="delivery-hint">Нужен сейчас, чтобы показать, какие товары в наличии</p><input id="delivery-address" name="address" type="text" autocomplete="street-address" placeholder="Куда доставить?" required><button class="primary delivery-submit" type="submit">Показать товары в наличии</button></form></dialog>`);
const renderers={home:homePage,catalog:catalogPage,product:detailPage,cart:cartPage,about:()=>infoPage('about'),delivery:()=>infoPage('delivery'),payment:()=>infoPage('payment'),contacts:()=>infoPage('contacts')};
document.querySelector('#page-content').innerHTML=(renderers[page]||homePage)();updateHeader();
document.querySelector('#login-button')?.addEventListener('click',()=>document.querySelector('#login-dialog').showModal());document.querySelector('#login-dialog .dialog-close').addEventListener('click',()=>document.querySelector('#login-dialog').close());document.querySelector('#login-form').addEventListener('submit',event=>{event.preventDefault();document.querySelector('#login-dialog').close();alert('Вход в демоверсии недоступен.')});
const deliveryDialog=document.querySelector('#delivery-dialog');const deliveryAddress=document.querySelector('#delivery-address');try{deliveryAddress.value=localStorage.getItem('tmb-address')||''}catch{};function openDeliveryDialog(){if(!deliveryDialog.open){deliveryDialog.showModal();requestAnimationFrame(()=>deliveryAddress.focus())}}document.querySelector('#address-input')?.addEventListener('click',openDeliveryDialog);document.querySelector('[data-close-delivery]')?.addEventListener('click',()=>deliveryDialog.close());
document.querySelectorAll('[data-delivery-mode]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-delivery-mode]').forEach(item=>{const active=item===button;item.classList.toggle('is-active',active);item.setAttribute('aria-pressed',String(active))})}));
document.querySelector('#delivery-form').addEventListener('submit',event=>{event.preventDefault();const value=deliveryAddress.value.trim();if(!value)return;try{localStorage.setItem('tmb-address',value)}catch{}const headerAddress=document.querySelector('#address-input');if(headerAddress)headerAddress.value=value;deliveryDialog.close()});
document.addEventListener('click',event=>{if(event.target.closest('.notice-close')){document.querySelector('#delivery-notice')?.remove();return}const favoriteButton=event.target.closest('[data-favorite]');if(favoriteButton){const id=favoriteButton.dataset.favorite;favorites=isFavorite(id)?favorites.filter(item=>item!==id):[...favorites,id];try{localStorage.setItem('tmb-favorites',JSON.stringify(favorites))}catch{}const selected=isFavorite(id);favoriteButton.classList.toggle('is-favorite',selected);favoriteButton.textContent=selected?'♥':'♡';favoriteButton.setAttribute('aria-pressed',String(selected));favoriteButton.setAttribute('aria-label',`${selected?'Убрать из':'Добавить в'} избранное: ${products.find(p=>p.id===id)?.name||'товар'}`);return}const addButton=event.target.closest('[data-add]');if(addButton){add(addButton.dataset.add);const detailQty=document.querySelector('#detail-qty');if(detailQty)detailQty.textContent=qty(addButton.dataset.add);if(page==='product')addButton.textContent=`В корзине: ${qty(addButton.dataset.add)} · добавить ещё`;else if(addButton.closest('.product-actions'))addButton.textContent='В корзину';else addButton.textContent=qty(addButton.dataset.add);openDeliveryDialog();return}const cartButton=event.target.closest('[data-cart]');if(cartButton){add(cartButton.dataset.id,cartButton.dataset.cart==='plus'?1:-1);document.querySelector('#page-content').innerHTML=cartPage();return}if(event.target.id==='clear-cart'){cart={};saveCart();document.querySelector('#page-content').innerHTML=cartPage();updateHeader()}if(event.target.id==='checkout'){const dialog=document.querySelector('#checkout-dialog');if(dialog)dialog.showModal()}if(event.target.id==='catalog-shortcut')location.href='catalog.html'});
document.addEventListener('click',event=>{const arrow=event.target.closest('[data-scroll-rail]');if(arrow){const railElement=document.getElementById(arrow.dataset.scrollRail);if(railElement)railElement.scrollBy({left:Math.max(280,railElement.clientWidth*.8),behavior:'smooth'})}});
document.addEventListener('change',event=>{if(event.target.id==='sort-products'){const params=new URLSearchParams(location.search);const cat=params.get('category')||'all';const badge=params.get('badge');let list=products.filter(p=>(cat==='all'||p.group===cat)&&(!badge||p[badge]));if(event.target.value==='cheap')list.sort((a,b)=>a.price-b.price);if(event.target.value==='expensive')list.sort((a,b)=>b.price-a.price);document.querySelector('#catalog-products').innerHTML=productGrid(list)}});
document.addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target.id==='site-search'&&event.target.value.trim()){location.href=`catalog.html?q=${encodeURIComponent(event.target.value.trim())}`}});
const query=new URLSearchParams(location.search).get('q');if(page==='catalog'&&query){const matching=products.filter(p=>`${p.name} ${p.category}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));document.querySelector('#catalog-products').innerHTML=productGrid(matching);document.querySelector('#catalog-count').textContent=`Результаты поиска «${query}»: ${matching.length}`;document.querySelector('h1').textContent=`Поиск: ${query}`}
if(query&&document.querySelector('#site-search'))document.querySelector('#site-search').value=query;
const addressInput=document.querySelector('#address-input');try{addressInput.value=localStorage.getItem('tmb-address')||''}catch{}
